language: swift
osx_image: xcode9.3
script: xcodebuild clean && xcodebuild build -sdk iphonesimulator11.3 -project TestingTravis.xcodeproj -scheme TestingTravis -destination platform=iOS Simulator,name=iPhone X,OS=11.3 CODE_SIGNING_REQUIRED=NO
