language: swift
osx_image: xcode9.3
before_install:sudo gem install cocoapods
install:pod install
script: xcodebuild clean && xcodebuild build -sdk iphonesimulator11.3 -workspace TestingTravis.xcworkspace -scheme TestingTravis -destination "platform=iOS Simulator,id=9F215ABB-F15F-4925-8E5E-760932B0BEF1,OS=11.3" CODE_SIGNING_REQUIRED=NO test
